const prompt = require("prompt-sync")();
let mois = prompt("Entrer le numéro de mois :");
switch (mois) {
    case "1" : console.log("Janvier (31 jours)");
    break;
    case "2" : console.log("Février (28 ou 29 jours)");
    break;
    case "3" : console.log("Mars (31 jours)");
    break;
    case "4" : console.log("Avril (30 jours)");
    break;
    case "5" : console.log("Mai (31 jours)");
    break;
    case "6" : console.log("Juin (30 jours)");
    break;
    case "7" : console.log("Juillet (31 jours)");
    break;
    case "8" : console.log("Août (31 jours)");
    break;
    case "9" : console.log("Septembre (30 jours)");
    break;
    case "10" : console.log("Octobre (31 jours)");
    break;
    case "11" : console.log("Novembre (30 jours)");
    break;
    case "12" : console.log("Décembre (31 jours)");
    break;
    default : console.log("nombere invalide");
};